name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd fastapi-aws-app
            git pull origin main
            source venv/bin/activate
            pkill -f uvicorn || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &
